const info = {
  info: [
    {
      id: 1,
      name: "Jenny Chan",
      brand: "3 waterfoot road",
      category: "333-962-7516",
      stock: 34,
      qSold: 32,
      inStock: 32,
      costPrice: 43,
      totalCost: 43,
      sellingPrice: 55,
      totalSales: 43,
      salesWithTaxes: 43,
      expense: 43,
      depts: 43,
      profit: 43,
      comments: "dtyiivb byuo",
    },
    {
      id: 2,
      name: "Jenny Chan",
      brand: "3 waterfoot road",
      category: "333-962-7516",
      stock: 34,
      qSold: 32,
      inStock: 32,
      costPrice: 43,
      totalCost: 43,
      sellingPrice: 43,
      totalSales: 43,
      salesWithTaxes: 43,
      expense: 43,
      depts: 43,
      profit: 43,
      comments: "dtyiivb byuo",
    },
    {
      id: 3,
      name: "Jenny Chan",
      brand: "3 waterfoot road",
      category: "333-962-7516",
      stock: 34,
      qSold: 32,
      inStock: 32,
      costPrice: 43,
      totalCost: 43,
      sellingPrice: 43,
      totalSales: 43,
      salesWithTaxes: 43,
      expense: 43,
      depts: 43,
      profit: 43,
      comments: "dtyiivb byuo",
    },
    {
      id: 4,
      name: "Jenny Chan",
      brand: "3 waterfoot road",
      category: "333-962-7516",
      stock: 34,
      qSold: 32,
      inStock: 32,
      costPrice: 43,
      totalCost: 43,
      sellingPrice: 43,
      totalSales: 43,
      salesWithTaxes: 43,
      expense: 43,
      depts: 43,
      profit: 43,
      comments: "dtyiivb byuo",
    },
  ],
};

export default info;
